### PR TITLE
alphabetize redux action creators, constants, and reducers (& their tests)

### PR DESCRIPTION
**Pull request by jebeck**
For an easy method of organizing things that's not open to interpretation and, more importantly, an easy way to flip back and forth between source and tests to see what's missing in the tests.

Thoughts welcome @krystophv @hntrdglss

### CODE REVIEW

**Comment by jebeck** [comment]
[<ux: 2 dev:8 tst:2> CGM Trends 2b - Implement exposing full CGM date traces](https://trello.com/c/AefCI0rV/82-ux-2-dev-8-tst-2-cgm-trends-2b-implement-exposing-full-cgm-date-traces)

**Comment by jebeck** [comment]
Since the PR this is branched off is probably getting tossed, can I inquire as to your thoughts @krystophv and @hntrdglss about this approach before I redo similar from my next branch?

**Comment by krystophv** [comment]
This looks fine to me as a strategy/code style guideline going forward.

**Comment by hntrdglss** [comment]
Yes, I concur.

**Pull request closed without merging**
