### PR TITLE
updated color of std deviation stat to match others in aggregated stats

### PR DESCRIPTION
**Pull request by thacherT1D**

### CODE REVIEW

**Comment by thacherT1D** [comment]
[[v1.16.0] Swap font families in app.tidepool from Open Sans to Basis](https://trello.com/c/nCSk7Bn6/541-v1160-swap-font-families-in-apptidepool-from-open-sans-to-basis)

**Comment by cbwebdevelopment** [comment]
@thacherT1D There are 4 failing tests.  Can you please update/fix them and ping me again for review?

**Comment by thacherT1D** [comment]
tests not passing, fixing locally

**Comment by thacherT1D** [comment]
@cbwebdevelopment passing tests

**Pull request merged**
